import { Dimensions, StyleSheet } from 'react-native';

const { width, height } = Dimensions.get('window');

export const loginStyles = StyleSheet.create({
    container: {
        flex: 1,
    },
    gradientBackground: {
        flex: 1,
    },
    backgroundCircle1: {
        position: 'absolute',
        width: width * 1.2,
        height: width * 1.2,
        borderRadius: width * 0.6,
        backgroundColor: 'rgba(41, 182, 209, 0.1)',
        top: -width * 0.4,
        right: -width * 0.3,
    },
    backgroundCircle2: {
        position: 'absolute',
        width: width * 0.8,
        height: width * 0.8,
        borderRadius: width * 0.4,
        backgroundColor: 'rgba(41, 182, 209, 0.08)',
        bottom: height * 0.1,
        left: -width * 0.2,
    },
    scrollContainer: {
        flexGrow: 1,
        justifyContent: 'center',
        gap: 8,
    },
    headerContainer: {
        alignItems: 'center',
        marginBottom: 32,
        paddingTop: 40,
    },
    logoContainer: {
        width: 100,
        height: 100,
        marginBottom: 20,
        // shadowColor: '#000',
        elevation: 0,
    },
    logoImage: {
        width: 100,
        height: 100,
    },
    title: {
        fontSize: 32,
        fontWeight: '700',
        color: '#FFFFFF',
        marginBottom: 8,
        textShadowColor: 'rgba(0, 0, 0, 0.15)',
        textShadowOffset: { width: 0, height: 1 },
        textShadowRadius: 3,
    },
    subtitle: {
        fontSize: 16,
        color: 'rgba(255, 255, 255, 0.9)',
        textAlign: 'center',
        fontWeight: '500',
    },
    formCard: {
        backgroundColor: '#FFFFFF',
        marginHorizontal: 24,
        borderRadius: 24,
        padding: 24,
        // shadowColor: '#000',
        elevation: 0,
    },
    formTitle: {
        fontSize: 20,
        fontWeight: '600',
        color: '#1A2B3C',
        marginBottom: 24,
        textAlign: 'center',
    },
    avatarContainer: {
        width: 100,
        height: 100,
        borderRadius: 50,
        backgroundColor: '#5F60B9',
        alignItems: 'center',
        justifyContent: 'center',
        alignSelf: 'center',
        marginBottom: 4,
    },
    inputContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#F7F7FB',
        borderRadius: 8,
        paddingHorizontal: 12,
        marginBottom: 10,
        height: 55,
    },
    input: {
        flex: 1,
        fontSize: 16,
        color: '#1C1F34',
        marginLeft: 1,
    },
    optionsContainer: {
        flexDirection: 'row',
        justifyContent: 'flex-end',
        alignItems: 'center',
        marginBottom: 24,
        marginTop: -8,
    },
    rememberMeContainer: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    checkbox: {
        width: 20,
        height: 20,
        borderRadius: 5,
        borderWidth: 2,
        borderColor: '#5F60B9',
        marginRight: 8,
        alignItems: 'center',
        justifyContent: 'center',
    },
    checkboxChecked: {
        backgroundColor: '#5F60B9',
    },
    rememberMeText: {
        fontSize: 14,
        color: '#1C1F34',
    },
    forgotPasswordText: {
        fontSize: 13,
        fontWeight: '600',
        color: '#29B6D1',
    },
    loginButton: {
        backgroundColor: '#29B6D1',
        paddingVertical: 16,
        borderRadius: 14,
        alignItems: 'center',
        marginBottom: 16,
        // shadowColor: '#29B6D1',
        elevation: 0,
    },
    loginButtonDisabled: {
        backgroundColor: '#E0E0E0',
        paddingVertical: 16,
        borderRadius: 14,
        alignItems: 'center',
        marginBottom: 16,
    },
    signupButton: {
        marginTop: 50,
        backgroundColor: '#29B6D1',
        paddingVertical: 15,
        borderRadius: 12,
        alignItems: 'center',
        marginBottom: 10,
    },
    loginButtonText: {
        color: '#FFFFFF',
        fontSize: 16,
        fontWeight: '700',
        letterSpacing: 1,
    },
    signupContainer: {
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        marginTop: 24,
    },
    signupText: {
        fontSize: 14,
        color: '#666666',
    },
    signupLink: {
        fontSize: 14,
        fontWeight: '700',
        color: '#29B6D1',
        marginLeft: 5,
        textDecorationLine: 'underline',
    },
    dividerContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 30,
    },
    dividerLine: {
        flex: 1,
        height: 1,
        backgroundColor: '#E0E0E0',
    },
    dividerText: {
        marginHorizontal: 15,
        fontSize: 14,
        color: '#8F8F8F',
    },
    socialLoginContainer: {
        flexDirection: 'row',
        justifyContent: 'center',
    },
    socialButton: {
        width: 50,
        height: 50,
        borderRadius: 25,
        backgroundColor: '#F7F7FB',
        alignItems: 'center',
        justifyContent: 'center',
        marginHorizontal: 15,
    },
    errorText: {
        color: '#D63031',
        fontSize: 13,
        marginTop: -12,
        marginBottom: 12,
    },
    // Bottom Sheet Styles for Forgot Password
    bottomSheetContent: {
        padding: 20,
        backgroundColor: '#FFFFFF',
    },
    inputLabel: {
        fontSize: 14,
        color: '#8F8F8F',
        marginBottom: 8,
        fontWeight: '500',
    },
    amountInput: {
        backgroundColor: '#F7F7FB',
        borderRadius: 12,
        padding: 15,
        fontSize: 18,
        color: '#1C1F34',
        borderWidth: 1,
        borderColor: '#E0E0E0',
        marginBottom: 20,
    },
    continueButton: {
        backgroundColor: '#29B6D1',
        paddingVertical: 14,
        borderRadius: 12,
        alignItems: 'center',
        marginTop: 10,
    },
    continueButtonText: {
        color: '#FFFFFF',
        fontSize: 16,
        fontWeight: 'bold',
    },
});
